apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test-app
  template:
    metadata:
      labels:
        app: jenkins-test-app
    spec:
      containers:
        - name: jenkins-test-app
          image: mitabhay002/jenkins-test-app-pipeline:1.0.0-24
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
