apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-app-service
  labels:
    app: jenkins-test-app 
spec:
  selector:
    app: jenkins-test-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
